---
- hosts: localhost
  connection: local
  gather_facts: no
  environment:
    PATH: "$PATH:/home/ec2-user/terraform/"

- name: confirm
  pause:
      prompt: "Type for the condition plan or plan_execute or execute?"
  register: terraform_phase

  tasks:
    - name: terraform init
      command: /home/ec2-user/terraform/terraform init
      args:
        chdir: terraform/

    - name: terraform phase
      terraform:
        project_path: "terraform/"
        plan_file: "/home/ec2-user/terraform_ansible_project/terraform/myplan.tfplan"
        state: planned
      when: hostvars['localhost']['terraform_phase']['user_input'] == 'plan'
      register: plan_results
