---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: terraform init
      command: terraform init /home/ec2-user/terraform_ansible_project/terraform

    - name: terraform plan
      terraform:
        project_path: "terraform/"
        plan_file: "myplan.tfplan"
        state: planned
      register: plan_results
