---
- hosts: localhost
  connection: local
  gather_facts: no
  environment:
    PATH: "$PATH:/home/ec2-user/terraform/"

  tasks:
    - name: terraform init
      command: /home/ec2-user/terraform/terraform init
      args:
        chdir: terraform/

    - name: terraform plan
      terraform:
#        project_path: "terraform/"
        command: /home/ec2-user/terraform/terraform plan
#        plan_file: "terraform-execution-state/myplan.tfplan"
        state: planned
      register: plan_results
