---
- hosts: localhost
  connection: local
  gather_facts: no


  - name: terraform plan
    terraform:
      project_path: "/"
      plan_file: "myplan.tfplan"
      state: planned
    register: plan_result
