---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: terraform init
      content: 'PATH=$PATH:/home/ec2-user/terraform'
      command: /home/ec2-user/terraform/terraform init
      args:
        chdir: terraform/

    - name: terraform plan
      terraform:
        project_path: "terraform/"
        plan_file: "myplan.tfplan"
        state: planned
      register: plan_results
