---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: terraform init
      project_path: "terraform/"
      command: terraform init

    - name: terraform plan
      terraform:
        project_path: "terraform/"
        plan_file: "myplan.tfplan"
        state: planned
      register: plan_results
