---
- hosts: localhost
  connection: local
  gather_facts: no
  environment:
    PATH: "$PATH:/home/ec2-user/terraform/"
  vars_prompt:
    - name: "terraform_phase"
      prompt: "Type for the condition plan or plan_execute or execute"
      private: no

  tasks:
    - name: terraform init
      command: /home/ec2-user/terraform/terraform init
      args:
        chdir: terraform/



    - name: terraform apply
      terraform:
        project_path: "terraform/"
        state: present
      when: terraform_phase == "apply"
      register: plan_results
