---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: terraform plan
      terraform:
        project_path: "/"
        plan_file: "myplan.tfplan"
        state: planned
      register: plan_results
